### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Miladiir** [joerncodes/obsidian-readwise-reader#22]
Thanks for this project. I have not tried it out, but wanted to say thanks anyway.

I am wondering: What is your workflow like? What do you use this for? Anyway, the idea is pretty cool.

**Comment by joerncodes** [comment]
Hi @Miladiir !

The way my workflow is set up, I use Obsidian for all notes I think will come in handy in the future. As someone who has seen some of their favorite websites die, I make sure to save important content redundantly in a system I have control over. This includes, for example, blog posts that stand out to me, recipes, or book summaries from sites like [Blinkist](https://www.blinkist.com/). 

Readwise, on the other hand, is my repository for highlights (which then sync to Obsidian). I wanted a way to get content I want to highlight into Readwise without relying on the content being hosted somewhere else. In the example of Blinkist, Readwise doesn't have a way to sync highlights from Blinkist to Readwise (and also, I don't have a paid Blinkist account anymore).

To highlight another workflow, I talked to people from the Readwise team, and they said they use my plugin to get note files with a list of ideas into Reader and then highlight them there to get them into the Readwise spaced repetition.
